#!/bin/bash
#SBATCH --job-name bowBuild
#SBATCH --partition docker
#SBATCH --time UNLIMITED
#SBATCH --mincpus 16
#SBATCH --mem-per-cpu 4g
#SBATCH --output /home/dbortone/scratch/bow_build_output.txt
#SBATCH --error /home/dbortone/scratch/bow_build_error.txt


docker run --rm=true \
  -v /datastore:/datastore:shared \
  dockerreg.bioinf.unc.edu:5000/bowtie2_2.3.3.1:1 bash -c \
    'bowtie2-build \
      --threads 16 \
      /datastore/nextgenout2/share/labs/imgf/ref/hg38/hg38.fa \
      /datastore/nextgenout2/share/labs/imgf/ref/hg19_bowtie2-build/'

# dunno why these needed to be renamed
mv /datastore/nextgenout2/share/labs/imgf/ref/hg19_bowtie2-build/.1.bt2 bowtie2-hg19.1.bt2
mv /datastore/nextgenout2/share/labs/imgf/ref/hg19_bowtie2-build/.2.bt2 bowtie2-hg19.2.bt2
mv /datastore/nextgenout2/share/labs/imgf/ref/hg19_bowtie2-build/.3.bt2 bowtie2-hg19.3.bt2
mv /datastore/nextgenout2/share/labs/imgf/ref/hg19_bowtie2-build/.4.bt2 bowtie2-hg19.4.bt2
mv /datastore/nextgenout2/share/labs/imgf/ref/hg19_bowtie2-build/.rev.1.bt2 bowtie2-hg19.rev.1.bt2
mv /datastore/nextgenout2/share/labs/imgf/ref/hg19_bowtie2-build/.rev.2.bt2 bowtie2-hg19.rev.2.bt2