#!/bin/bash
#SBATCH --job-name bowBuild
#SBATCH --partition docker
#SBATCH --time UNLIMITED
#SBATCH --mincpus 16
#SBATCH --mem-per-cpu 2g
#SBATCH --output /home/dbortone/scratch/bow_build_output.txt
#SBATCH --error /home/dbortone/scratch/bow_build_error.txt

docker run --rm=true \
  -v /datastore:/datastore:shared \
  dockerreg.bioinf.unc.edu:5000/bowtie2_2.3.3.1:1 bash -c \
    'bowtie2-build \
      --threads 8 \
      /datastore/nextgenout2/share/labs/imgf/ref/hg38/hg38.fa \
      /datastore/nextgenout2/share/labs/imgf/ref/bowtie2-build/'
